<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0
        </TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="QuestPDF" Version="2025.12.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
        <ProjectReference Include="..\DomainDetective.Reports\DomainDetective.Reports.csproj" />
    </ItemGroup>

</Project>
