<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <VersionPrefix>0.2.0</VersionPrefix>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0;net10.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0;net10.0
        </TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
        <ProjectReference Include="..\DomainDetective.Reports\DomainDetective.Reports.csproj" />
    </ItemGroup>

    <!-- Use NuGet package for all TFMs -->
    <ItemGroup>
        <PackageReference Include="OfficeIMO.Markdown" Version="3.2.0" />
    </ItemGroup>

</Project>
