<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <VersionPrefix>0.2.0</VersionPrefix>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0;net10.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0;net10.0
        </TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DBAClientX.PostgreSql" Version="1.0.8" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DomainDetective.Tests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DomainDetective.CtSql.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
