@{
    AliasesToExport      = @('Add-DnsblProvider', 'Clear-DnsblProvider', 'New-DDSecurityReport', 'Get-CertificateInfo', 'Get-DomainFlattenedSpfIp', 'Get-IdpInfo', 'Get-RdapObject', 'Get-SearchEngineInfo', 'Get-DomainWhois', 'Get-DmarcAggregateTimeSeries', 'Get-TlsRptReportsTimeSeries', 'Get-RegistrationDrift', 'Import-DmarcForensic', 'Import-DmarcReport', 'Import-DmarcAggregateSnapshot', 'Import-RegistrationSnapshot', 'Import-DnsblConfig', 'Import-EmailTlsRpt', 'Import-TlsRpt', 'Import-TlsRptReportSnapshot', 'Invoke-DomainWizard', 'New-DmarcRecord', 'Remove-DnsblProvider', 'Set-ExportOptions', 'Set-DDNarrator', 'Start-DnsPropagationMonitor', 'Start-UptimeMonitor', 'Stop-DnsPropagationMonitor', 'Stop-UptimeMonitor', 'Test-EmailArc', 'Test-EmailAutoDiscover', 'Test-EmailBimi', 'Test-DnsBlacklist', 'Test-DnsDomainBlacklist', 'Test-DDDnsDomainBlacklist', 'Test-DDDnsBlacklistRecord', 'Test-DnsCaa', 'Test-DomainContact', 'Test-TlsDane', 'Test-DnsDanglingCname', 'Test-DnsDelegation', 'Test-Delegation', 'Test-DirectoryExposure', 'Test-EmailDkim', 'Test-EmailDmarcAggregate', 'Test-DmarcAggregate', 'Test-EmailDmarc', 'Test-DnsHealth', 'Test-DnsPropagation', 'Test-DnsSec', 'Test-DnsTtl', 'Test-DnsTunneling', 'Test-DomainHealth', 'Test-DnsEdnsSupport', 'Test-EmailProtocolTls', 'Test-MailTls', 'Test-DnsFcrDns', 'Test-EmailImapTls', 'Test-ImapTls', 'Test-NetworkIpNeighbor', 'Test-EmailLatency', 'Get-EmailHeaderInfo', 'Test-EmailMtaSts', 'Test-DnsMx', 'Test-MxRecord', 'Test-DnsNs', 'Test-EmailOpenRelay', 'Test-DnsOpenResolver', 'Test-OpenResolver', 'Test-EmailPop3Tls', 'Test-Pop3Tls', 'Test-NetworkPortAvailability', 'Test-NetworkPortScan', 'Get-Rdap', 'Test-Rdap', 'Test-DnsReverseDns', 'Test-ReverseDns', 'Test-Rpki', 'Test-DomainSecurityTxt', 'Test-DnsSmimea', 'Test-EmailSmtpAuth', 'Test-EmailSmtpBanner', 'Test-SmtpBanner', 'Test-EmailSmtpTls', 'Test-DnsSoa', 'Test-SpfHost', 'Test-EmailSpf', 'Test-EmailStartTls', 'Test-DomainThreatIntel', 'Test-EmailTlsRpt', 'Test-Website', 'Test-DomainCertificate', 'Test-WebsiteSecurity', 'Test-WebsiteStaticScan', 'Test-WebStaticScan', 'Test-DDWebStaticScan', 'Test-DnsWildcard', 'Test-DnsZoneTransfer', 'Test-ZoneTransfer')
    Author               = 'Przemyslaw Klys'
    CmdletsToExport      = @('Add-DDDnsblProvider', 'Clear-DDDnsblProviderList', 'Export-DDSecurityReport', 'Get-DDApexAddressInfo', 'Get-DDTlsCertificateInfo', 'Get-DDDomainFlattenedSpfIp', 'Get-DDIdpInfo', 'Test-DDMailDomainClassification', 'Get-DDRdapObject', 'Get-DDSearchEngineInfo', 'Get-DDDomainWhois', 'Get-DDDmarcAggregateTimeSeries', 'Get-DDTlsRptReportsTimeSeries', 'Get-DDRegistrationDrift', 'Import-DDDmarcForensic', 'Import-DDDmarcReport', 'Import-DDDmarcAggregateSnapshot', 'Import-DDRegistrationSnapshot', 'Import-DDDnsblConfig', 'Import-DDEmailTlsRpt', 'Import-DDTlsRptReportSnapshot', 'Invoke-DDDomainWizard', 'New-DDDmarcRecord', 'Remove-DDDnsblProvider', 'Set-DDExportOptions', 'Set-DDPersona', 'Start-DDDnsPropagationMonitor', 'Start-DDUptimeMonitor', 'Stop-DDDnsPropagationMonitor', 'Stop-DDUptimeMonitor', 'Test-DDEmailArcRecord', 'Test-DDEmailAutoDiscover', 'Test-DDEmailBimiRecord', 'Test-DDDnsBlacklist', 'Test-DDDnsCaaRecord', 'Test-DDDomainContactRecord', 'Test-DDTlsDaneRecord', 'Test-DDDnsDanglingCname', 'Test-DDDnsDelegation', 'Test-DDDirectoryExposure', 'Test-DDEmailDkimRecord', 'Test-DDDmarcAggregate', 'Test-DDEmailDmarcRecord', 'Test-DDDnsHealth', 'Test-DDDnsPropagation', 'Test-DDDnsSecStatus', 'Test-DDDnsTtl', 'Test-DDDnsTunneling', 'Test-DDDomainOverallHealth', 'Test-DDDnsEdnsSupport', 'Test-DDEmailProtocolTls', 'Test-DDDnsForwardReverse', 'Test-DDEmailImapTls', 'Test-DDNetworkIpNeighbor', 'Test-DDEmailLatency', 'Get-DDEmailMessageHeaderInfo', 'Test-DDEmailMtaSts', 'Test-DDDnsMxRecord', 'Test-DDDnsNsRecord', 'Test-DDEmailOpenRelay', 'Test-DDDnsOpenResolver', 'Test-DDEmailPop3Tls', 'Test-DDNetworkPortAvailability', 'Test-DDNetworkPortScan', 'Get-DDRdap', 'Test-DDDnsReverseDns', 'Test-DDRpki', 'Test-DDDomainSecurityTxt', 'Test-DDDnsSmimeaRecord', 'Test-DDEmailSmtpAuth', 'Test-DDEmailSmtpBanner', 'Test-DDEmailSmtpTls', 'Test-DDDnsSoaRecord', 'Test-DDSpfHost', 'Test-DDEmailSpfRecord', 'Test-DDEmailStartTls', 'Test-DDDomainThreatIntel', 'Test-DDEmailTlsRptRecord', 'Test-DDWebsite', 'Test-DDDomainCertificate', 'Test-DDWebsiteSecurity', 'Test-DDWebsiteStaticScan', 'Test-DDDnsWildcard', 'Test-DDDnsZoneTransfer')
    CompanyName          = 'Evotec'
    CompatiblePSEditions = @('Desktop', 'Core')
    Copyright            = '(c) 2011 - 2025 Przemyslaw Klys @ Evotec. All rights reserved.'
    Description          = 'DomainDetective is a PowerShell module that provides features to work with domains, DNS, and other related information.'
    FunctionsToExport    = @()
    GUID                 = 'a2986f0d-da11-43f5-a252-f9e1d1699776'
    ModuleVersion        = '0.2.0'
    PowerShellVersion    = '5.1'
    PrivateData          = @{
        PSData = @{
            ProjectUri               = 'https://github.com/EvotecIT/DomainDetective'
            RequireLicenseAcceptance = $false
            Tags                     = @('Windows', 'MacOS', 'Linux')
        }
    }
    RootModule           = 'DomainDetective.psm1'
}
