<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;net8.0</TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="OfficeIMO.Word" Version="1.0.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
        <ProjectReference Include="..\DomainDetective.Reports\DomainDetective.Reports.csproj" />
    </ItemGroup>

</Project>
