<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <VersionPrefix>0.2.0</VersionPrefix>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0;net10.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0;net10.0
        </TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OfficeIMO.Word" Version="1.0.62" />
        <PackageReference Include="OfficeIMO.Excel" Version="0.6.41" />
        <!-- <ProjectReference Include="..\..\OfficeIMO\OfficeIMO.Excel\OfficeIMO.Excel.csproj" /> -->
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
    <ProjectReference Include="..\DomainDetective.Reports\DomainDetective.Reports.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="IsExternalInit.cs" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <Compile Include="IsExternalInit.cs" />
  </ItemGroup>

</Project>
