<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0
        </TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DnsClientX" Version="1.0.7" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.13.0" />
        <PackageReference Include="PgpCore" Version="6.5.3" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.IO.Compression.FileSystem" />
        <Reference Include="System.ComponentModel.DataAnnotations" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Dictionaries\" />
    </ItemGroup>
    <ItemGroup>
        <!-- DNSBL list is built into the code. Use LoadDNSBL to load external files if required. -->
        <EmbeddedResource Include="..\Data\dnsbl.json" LogicalName="DomainDetective.dnsbl.json" />
        <EmbeddedResource Include="..\Data\DNS\PublicDNS.json"
            LogicalName="DomainDetective.DNS.PublicDNS.json" />
        <EmbeddedResource Include="..\Data\geoip.csv" />
        <AdditionalFiles Include="..\Data\DNS\PublicDNS.json" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>DomainDetective.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="..\Data\public_suffix_list.dat" />
        <EmbeddedResource Include="..\Data\takeover.json" />
        <EmbeddedResource Include="..\Data\directory_paths.json" />
        <None Include="..\Data\hsts_preload.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective.Generators\DomainDetective.Generators.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Definitions\DmarcAggregateReport_v1.xsd" />  
        <EmbeddedResource Include="Definitions\DmarcAggregateReport_v2.xsd" />  
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="DomainHealthCheck.Trim.cs" />
    </ItemGroup>
    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <Compile Include="DomainHealthCheck.Trim.cs" />
    </ItemGroup>

</Project>
