<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`Windows`))' ">
            net472;net8.0;net10.0
        </TargetFrameworks>
        <TargetFrameworks Condition=" '$([MSBuild]::IsOsPlatform(`OSX`))' Or '$([MSBuild]::IsOsPlatform(`Linux`))' ">
            net8.0;net10.0
        </TargetFrameworks>
        <LangVersion>Latest</LangVersion>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DomainDetective\DomainDetective.csproj" />
        <PackageReference Include="PgpCore" Version="6.5.4" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
        <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.IO.Compression.FileSystem" />
        <Reference Include="System.ComponentModel.DataAnnotations" />
    </ItemGroup>

</Project>
